version: '3.8'

services: 
  app:
    build: .
    depends_on: 
      - mysql
    links:
      - mysql
    ports:
      - "4200:4200"
  mysql: 
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
