version: '3.8'

services: 
  app:
    build: .
    container_name: nodes-server
    
    depends_on: 
      - mysql
    links:
      - mysql
    networks:
      - nodes-network
    ports:
      - "4200:4200"
  mysql: 
    image: mysql:5.7
    container_name: nodes-database
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nodes-network
    ports:
      - "3306:3306"
  shadow-db:
    image: mysql:5.7
    container_name: nodes-shadow-database
    environment: 
      MYSQL_ROOT_PASSWORD: ${SHADOW_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SHADOW_MYSQL_DATABASE}
      MYSQL_USER: ${SHADOW_MYSQL_USER}
      MYSQL_PASSWORD: ${SHADOW_MYSQL_PASSWORD}
    networks:
      - nodes-network
    ports:
      - "3307:3306"

networks:
  nodes-network:
